"""Validation for the Part 2 agent-authored semantic retrieval index."""

from __future__ import annotations

import re
from collections import defaultdict
from typing import Any


INDEX_SCHEMA_VERSION = 2
INDEX_GENERATOR = "part2_agent"

PART2_ROLES = {
    "historical",
    "projected",
    "input",
    "assumption",
    "linked",
    "calculation",
    "control",
    "output",
    "check",
    "header",
    "template",
    "scenario",
    "sensitivity",
}
PERIOD_TYPES = {"historical", "projected", "unspecified"}
ORIENTATIONS = {"row", "column", "block", "non_contiguous"}
CALCULATION_KINDS = {
    "input",
    "assumption",
    "linked",
    "calculation",
    "control",
    "check",
    "output",
    "header",
    "template",
    "sensitivity",
    "value",
}
RELATIONSHIP_TYPES = {"feeds", "linked_to", "component_of", "paired_with"}
_CELL_REFERENCE = re.compile(r"^[A-Z]{1,3}[1-9][0-9]*$")


def _nonempty_string(value: Any, *, context: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{context} must be a non-empty string")
    return value


def _string_list(
    value: Any,
    *,
    context: str,
    allow_empty: bool = True,
) -> list[str]:
    if (
        not isinstance(value, list)
        or (not allow_empty and not value)
        or not all(isinstance(item, str) and item.strip() for item in value)
        or len(value) != len(set(value))
    ):
        qualifier = "a unique non-empty" if not allow_empty else "a unique"
        raise ValueError(f"{context} must be {qualifier} string list")
    return value


def validate_subsection_index(
    payload: dict[str, Any],
    *,
    subsections: list[dict[str, Any]],
    eligible: set[tuple[str, str]],
) -> None:
    """Validate agent-authored families, lineage, coverage, and relationships."""

    expected_root = {"schema_version", "generated_by", "families", "relationships"}
    if not isinstance(payload, dict) or set(payload) != expected_root:
        raise ValueError("subsection_index.json has invalid root keys")
    if payload["schema_version"] != INDEX_SCHEMA_VERSION:
        raise ValueError("subsection_index.json has an unsupported schema version")
    if payload["generated_by"] != INDEX_GENERATOR:
        raise ValueError("subsection_index.json must be generated by the Part 2 agent")
    if not isinstance(payload["families"], list) or not payload["families"]:
        raise ValueError("subsection_index.json must contain families")
    if not isinstance(payload["relationships"], list):
        raise ValueError("subsection_index.json relationships must be a list")

    subsection_by_id = {
        subsection["subsection_id"]: subsection for subsection in subsections
    }
    required = {
        "family_id",
        "subsection_id",
        "parent_section_id",
        "sheet",
        "object_name",
        "aliases",
        "changed_cells",
        "anchor_cells",
        "roles",
        "scope",
        "orientation",
        "calculation_kind",
        "formula_signatures",
    }
    seen_families: set[str] = set()
    indexed_changed: dict[str, set[str]] = defaultdict(set)
    for index, family in enumerate(payload["families"]):
        context = f"families[{index}]"
        if not isinstance(family, dict) or set(family) != required:
            raise ValueError(f"{context} has invalid keys")

        family_id = _nonempty_string(family["family_id"], context=f"{context}.family_id")
        if family_id in seen_families:
            raise ValueError(f"{context} has a duplicate family_id")
        seen_families.add(family_id)

        subsection_id = _nonempty_string(
            family["subsection_id"], context=f"{context}.subsection_id"
        )
        subsection = subsection_by_id.get(subsection_id)
        if subsection is None:
            raise ValueError(f"{context} has an unknown subsection")
        if (
            family["parent_section_id"] != subsection["parent_section_id"]
            or family["sheet"] != subsection["sheet"]
        ):
            raise ValueError(f"{context} has invalid Part 2 lineage")

        _nonempty_string(family["object_name"], context=f"{context}.object_name")
        _string_list(family["aliases"], context=f"{context}.aliases")
        changed = _string_list(
            family["changed_cells"],
            context=f"{context}.changed_cells",
            allow_empty=False,
        )
        anchors = _string_list(
            family["anchor_cells"], context=f"{context}.anchor_cells"
        )
        if set(changed) & set(anchors):
            raise ValueError(f"{context} changed_cells and anchor_cells overlap")
        if not all(_CELL_REFERENCE.fullmatch(address) for address in changed + anchors):
            raise ValueError(f"{context} contains invalid A1 addresses")
        subsection_cells = set(subsection["cells"])
        invalid_changed = [
            address
            for address in changed
            if (family["sheet"], address) not in eligible
            or address not in subsection_cells
        ]
        if invalid_changed:
            raise ValueError(f"{context} contains invalid changed cells")
        if not set(anchors).issubset(subsection_cells):
            raise ValueError(f"{context} contains anchors outside its subsection")
        duplicate_coverage = indexed_changed[subsection_id] & set(changed)
        if duplicate_coverage:
            raise ValueError(f"{context} duplicates changed-cell family coverage")
        indexed_changed[subsection_id].update(changed)

        roles = _string_list(
            family["roles"], context=f"{context}.roles", allow_empty=False
        )
        if not set(roles).issubset(PART2_ROLES):
            raise ValueError(f"{context} contains unsupported roles")
        if not set(roles).issubset(set(subsection["roles"])):
            raise ValueError(f"{context} roles exceed its subsection roles")

        scope = family["scope"]
        if not isinstance(scope, dict) or set(scope) != {
            "period_type",
            "period_headers",
        }:
            raise ValueError(f"{context}.scope has invalid keys")
        if scope["period_type"] not in PERIOD_TYPES:
            raise ValueError(f"{context}.scope has an invalid period_type")
        headers = scope["period_headers"]
        if not isinstance(headers, list):
            raise ValueError(f"{context}.scope.period_headers must be a list")
        seen_headers: set[tuple[str, str]] = set()
        for header_index, header in enumerate(headers):
            header_context = f"{context}.scope.period_headers[{header_index}]"
            if not isinstance(header, dict) or set(header) != {"cell", "label"}:
                raise ValueError(f"{header_context} has invalid keys")
            cell = _nonempty_string(header["cell"], context=f"{header_context}.cell")
            label = _nonempty_string(
                header["label"], context=f"{header_context}.label"
            )
            if not _CELL_REFERENCE.fullmatch(cell):
                raise ValueError(f"{header_context}.cell is not uppercase A1")
            if (cell, label) in seen_headers:
                raise ValueError(f"{header_context} is duplicated")
            seen_headers.add((cell, label))

        if family["orientation"] not in ORIENTATIONS:
            raise ValueError(f"{context} has an invalid orientation")
        if family["calculation_kind"] not in CALCULATION_KINDS:
            raise ValueError(f"{context} has an invalid calculation_kind")
        _string_list(
            family["formula_signatures"],
            context=f"{context}.formula_signatures",
        )

    for subsection in subsections:
        expected = {
            address
            for address in subsection["cells"]
            if (subsection["sheet"], address) in eligible
        }
        if expected and indexed_changed[subsection["subsection_id"]] != expected:
            raise ValueError(
                f"subsection index does not cover {subsection['subsection_id']} changed cells"
            )

    relationship_keys = {"source_family_id", "target_family_id", "relationship"}
    seen_relationships: set[tuple[str, str, str]] = set()
    for index, relationship in enumerate(payload["relationships"]):
        context = f"relationships[{index}]"
        if not isinstance(relationship, dict) or set(relationship) != relationship_keys:
            raise ValueError(f"{context} has invalid keys")
        source = relationship["source_family_id"]
        target = relationship["target_family_id"]
        kind = relationship["relationship"]
        if source not in seen_families or target not in seen_families or source == target:
            raise ValueError(f"{context} has invalid family lineage")
        if kind not in RELATIONSHIP_TYPES:
            raise ValueError(f"{context} has an invalid relationship type")
        key = (source, target, kind)
        if key in seen_relationships:
            raise ValueError(f"{context} is duplicated")
        seen_relationships.add(key)
